name: pulse-chat

services:
  postgres:
    image: postgres:13
    container_name: pulse-postgres
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pulse
    ports:
      - "5432:5432"
    volumes:
      - pulse_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pulse-redis
    ports:
      - "6379:6379"
    volumes:
      - pulse_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: pulse-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - pulse_zookeeper_data:/data
      - pulse_zookeeper_log:/datalog

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: pulse-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - pulse_kafka_data:/var/lib/kafka/data

volumes:
  pulse_postgres_data:
  pulse_redis_data:
  pulse_zookeeper_data:
  pulse_zookeeper_log:
  pulse_kafka_data:
